//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mälupulga_varundamiskeskus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mälupulga_varundamiskeskus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///set &quot;action=%1&quot;
        ///set &quot;location=%2&quot;
        ///set &quot;location=%location:+= %&quot;
        ///set &quot;destination=%3&quot;
        ///set &quot;destination=%destination:+= %&quot;
        ///if &quot;%action%&quot; == &quot;count&quot; (
        ///	dir &quot;%location%&quot; /b /a /s&gt;%homedrive%\mas\bc_countlog.txt
        ///)
        ///if &quot;%action%&quot; == &quot;backup&quot; (
        ///	xcopy /E /C /A /H /R /K /Y &quot;%location%&quot; &quot;%destination%&quot;&gt;%homedrive%\mas\bc_filelog.txt
        ///)
        ///if &quot;%action%&quot; == &quot;restore&quot; (
        ///	xcopy /E /C /A /H /R /K /Y &quot;%location%&quot; &quot;%destination%&quot;&gt;%homedrive%\mas\bc_filelog.txt
        ///)
        ///.
        /// </summary>
        internal static string bc {
            get {
                return ResourceManager.GetString("bc", resourceCulture);
            }
        }
    }
}
